name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # 使用正确的 token 引用
          token: ${{ secrets.METRICS_TOKEN }}
          
          # 移除无效的 config 参数
          # 使用其他有效参数替代
          template: classic
          base: header, activity, community, repositories
          plugins: languages, stars
